Sabadell a #DATE#.
¡Gracias por formar parte del proyecto ISSUS!
Este contrato se celebra entre SCRAMBÒTIKA, SL. y todos los Usuarios de  , y cubren el uso y acceso a nuestros servicios, el software cliente y nuestros sitios web.
Si aceptas las presentes condiciones y continúas utilizando nuestro software, estás aceptando los requisitos sobre nuestra política comercial, de uso, de privacidad, de protección de datos y de cumplimiento legal, aquí detalladas.
1.	Nuestro Producto
Nuestros Servicios te permiten usar el software cliente (en adelante, "ISSUS"), que podría actualizarse automáticamente. Cumpliendo estas Condiciones, te concederemos una licencia limitada, revocable, no exclusiva e intransferible para usarlo, con la finalidad exclusiva de acceder a ISSUS. 
ISSUS está protegido por las leyes de copyright, marcas registradas y otras leyes españolas y europeas. Estas Condiciones no te conceden ningún derecho, titularidad o interés legítimo sobre ISSUS, el contenido de otros usuarios en ISSUS, las marcas registradas de ISSUS i SCRAMBÒTIKA, sus logotipos y otros elementos vinculados a la marca. 
SCRAMBÒTIKA, SL., B66178658, con domicilio fiscal en Sol, 1, 2-4, 08201 de Sabadell, es titular de los derechos de autor, marcas, derechos de propiedad intelectual, know-how y cuantos otros derechos que guarden relación con el servicio contratado.
Como cliente, en virtud del presente contrato, no adquieres absolutamente ningún derecho o licencia a propósito del producto ISSUS, de los programas de ordenador necesarios para la prestación del servicio ni tampoco sobre la información técnica de seguimiento del servicio, a excepción de los derechos y licencias necesarios para el cumplimiento del presente contrato y, únicamente, para la duración del mismo.
Para cualquier actuación que exceda del cumplimiento de este contrato necesitarás autorización por escrito por parte de SCRAMBÒTIKA.
2.	Versiones Iniciales o de Prueba (Versión Beta)
Esta primera versión inicial está en fase de prueba y evaluación final. Estos Servicios, denominados Beta, se consideran de acceso preliminar o evaluación y podrían no ser tan fiables como posteriores versiones definitivas, por lo que debe tenerse en cuenta.
Todos los Servicios beta pueden cambiarse o actualizarse en cualquier momento, sin previo aviso.
SCRAMBÒTIKA no asumirá ninguna responsabilidad derivada o relacionada con el uso de un producto en Versión Beta.
Para revisiones futuras y actualizaciones definitivas está previsto cobrar por el uso de nuestro software. Todos los cambios en las tarifas y precios serán siempre comunicados con anterioridad a los usuarios.
3.	La gestión de tus datos.
Al utilizar nuestros Servicios, nos proporcionas elementos como archivos, contenido, mensajes de correo, contactos, etc. (en adelante, "Contenido"). Tu Contenido es tuyo. Estas Condiciones no nos conceden derecho alguno sobre tu Contenido, excepto los derechos limitados que nos permiten ofrecer los Servicios.
Necesitamos tu permiso para acciones como almacenar tu Contenido, realizar copias de seguridad o compartirlo cuando lo solicites. Estas y otras funciones pueden requerir que nuestros sistemas accedan a tu Contenido, lo almacenen y lo examinen. Como usuario, nos concedes permiso para realizar estas actividades, que se extiende a nuestros afiliados y a terceras partes de plena confianza con las que podamos colaborar.
4.	Política de privacidad y protección de datos personales.
Recopilamos y utilizamos información y datos para proporcionar, mejorar y proteger nuestros Servicios. Utilizamos tecnologías como las cookies y etiquetas de píxel para proporcionar, mejorar, promocionar y proteger nuestros Servicios. La utilización de cookies en nuestros servicios tiene la única finalidad de interrelacionar los datos a través de los diferentes formularios. Las cookies son unos ficheros que se guardan en tu ordenador durante la visita a la página web, y son usados principalmente para facilitar el uso del servicio. Puedes configurar tu navegador para que no acepte cookies, pero esto podría limitar tu capacidad para usar nuestros servicios.
Compartimos información con proveedores que trabajan para SCRAMBÒTIKA. Confiamos en proveedores externos que nos ayudan a proporcionar, mejorar, promocionar y proteger nuestros Servicios. Estos proveedores podrán acceder a tu información exclusivamente para realizar tareas en nuestro nombre y de forma acorde con esta Política de privacidad.
Nunca facilitaremos tus datos a terceros con fines publicitarios ni de ningún otro tipo.
La custodia de tus datos es fundamental para nosotros, siendo una responsabilidad que aceptamos de buen grado. Los datos de nuestros usuarios deben recibir la misma protección legal tanto si están almacenados en nuestros servicios como si se encuentran en los discos duros de tus ordenadores. 
Conservaremos la información que almacenes en nuestros Servicios durante tanto tiempo como sea necesario para ofrecerte los Servicios. 
Si eliminas tu cuenta, borraremos toda la información. No obstante, ten en cuenta que quizá necesitemos un tiempo para borrarla de los Servicios y las copias de seguridad, y que conservaríamos la información necesaria para cumplir con nuestras obligaciones legales, resolver disputas o cumplir nuestros compromisos.
De los datos personales
En cumplimiento del Reglamento Europeo de Protección de datos (REPD) y de la legislación relacionada sobre protección de datos de carácter personal (LOPD), te informamos que tus datos personales y de contacto se incorporan a los ficheros informatizados titularidad de SCRAMBÒTIKA, con la finalidad de permitir todas las gestiones derivadas del presente contrato. 
Consentimiento y autorización al tratamiento automatizado de sus datos personales
En SCRAMBÒTIKA, como responsables de los ficheros, consideramos que en el momento que nos facilitas tus datos de carácter personal, mediante los diversos formularios que contiene nuestra página web o del correo electrónico, nos estás otorgando tu autorización y consentimiento expreso para el tratamiento de tus datos en nuestro fichero informatizado, si bien con carácter revocable y sin efectos retroactivos, y aceptas las presentes políticas de privacidad respecto a tus datos, que serán tratados con absoluta confidencialidad, cumpliendo todas las exigencias legales recogidas en el Reglamento Europeo de Protección de Datos y en la Ley Orgánica de Protección de Datos y demás legislación aplicable, quedando sometida a la misma todos los que utilicen nuestros servicios.
Derechos de acceso, rectificación, cancelación, oposición y olvido de tus datos personales
A los efectos de lo dispuesto en la legislación, tienes reconocidos y podrás ejercitar los derechos de acceso, cancelación, rectificación, oposición y olvido. A tal efecto, en cualquier momento tienes derecho a acceder gratuitamente a la información de nuestros ficheros automatizados para consultar tus datos, rectificarlos si son erróneos o han variado, cancelarlos si no deseas seguir incorporado a ellos, u oponerte. Para ello, puedes contactar con nosotros en el correo electrónico hola@scrambotika.com.
Actualización y Cancelación de tus datos
Es importante que para que podamos mantener tus datos personales actualizados, nos informes siempre que haya alguna modificación de los mismos, ya que, en caso contrario no respondemos de su veracidad. Asimismo, nos certifica que todos los datos que nos facilitas son ciertos, vigentes y pertinentes para la finalidad por la que te los solicitamos. Entendemos que, si no cancelas tus datos personales expresamente de nuestro fichero continúas interesado en seguir incorporado, hasta que SCRAMBÒTIKA lo considere oportuno y mientras resulte adecuado a la finalidad por la que se obtuvieron.
Garantía de Confidencialidad y Seguridad de los ficheros automatizados
SCRAMBÒTIKA, en respuesta a la confianza depositada en nosotros y teniendo en cuenta la importancia en materia de protección y confidencialidad que requieren tus datos personales, te informa que hemos adoptado todas las medidas de índole técnica y organizativa necesarias para salvaguardar la seguridad de los mismos, tal como exige el Real Decreto 1720/2007 que regula el reglamento de medidas de seguridad de los ficheros automatizados que contengan datos de carácter personal. No obstante, debes ser consciente de que las medidas de seguridad en Internet no son inexpugnables.
De los datos personales alojados en ISSUS
Eres el único responsable de los datos que alojes o puedas obtener a través de los servicios contratados con SCRAMBÒTIKA y por tanto, eres tú quien debe cumplir la legalidad vigente en relación con los datos personales.
SCRAMBÒTIKA puede modificar las presentes políticas de privacidad para adaptarlas a las medidas legislativas o jurisprudenciales sobre datos personales que vayan apareciendo, por lo que exige su lectura y aceptación, cada vez que nos facilites tus datos a través de nuestra Web o actualices ISSUS.
5.	Responsabilidades

De SCRAMBÒTIKA
En nuestras relaciones con los clientes, SCRAMBÒTIKA actúa con la diligencia debida en el uso de su actividad comercial, lealmente y de buena fe. SCRAMBÒTIKA se compromete a ofrecer de manera óptima sus servicios, con todos los medios a su alcance, esforzándose para que los mismos puedan desarrollarse durante 24 horas al día, 7 días a la semana de la manera más segura posible, a excepción de las incidencias que se produzcan fuera del control de SCRAMBÒTIKA. En este sentido SCRAMBÒTIKA se reserva el derecho de interrumpir el servicio contratado en función de reparaciones técnicas y de mantenimiento de los equipos, así como para la mejora de los propios servicios.
En la medida en que la ley lo permita, salvo responsabilidad de SCRAMBÒTIKA y de sus colaboradores por fraude, dolo o falta grave, en ningún caso será responsable SCRAMBÒTIKA, sus proveedores o distribuidores de:
(a) daños indirectos, especiales, fortuitos, punitivos, ejemplares o consecuentes, o
(b) pérdida de la utilización, datos, negocios o ganancias, independientemente de la condición jurídica.

Lo anteriormente mencionado será aplicable independientemente de si se ha avisado o no a SCRAMBÒTIKA o a sus colaboradores de la posibilidad de tales daños, e incluso si el remedio propuesto no cumpliera su finalidad esencial.
Asimismo, SCRAMBÒTIKA, sus afiliados, proveedores y distribuidores quedan exonerados de toda responsabilidad por aquellas reclamaciones relativas a los servicios, por un valor superior a la cantidad abonada a SCRAMBÒTIKA en los últimos 12 meses por los servicios contratados.
SCRAMBÒTIKA no es, en ningún caso, responsable de los contenidos que los usuarios almacenen o compartan mediante ISSUS.
En el caso de que hayas alojado ficheros con datos de carácter personal y aun así lo hayas notificado a SCRAMBÒTIKA, serás el único responsable de realizar las copias de seguridad reglamentarias para cumplir con la LOPD y bajo ningún concepto podrás exigir a SCRAMBÒTIKA ninguna responsabilidad derivada de cualquier fallo, error o descuido por la realización o no, de las mismas.
SCRAMBÒTIKA no es responsable de todo aquello que sea exclusivamente imputable a los clientes o usuarios.
SCRAMBÒTIKA no garantiza que la prestación del servicio objeto de este contrato sea continua e ininterrumpida por circunstancias originadas por problemas en la red de Internet, averías en los dispositivos informáticos y cualquier otra circunstancia imprevisible. Por consiguiente, aceptas soportar dentro de unos límites razonables estas circunstancias, por lo que renuncias expresamente a reclamar a SCRAMBÒTIKA cualquier responsabilidad contractual o extracontractual por los posibles fallos, errores y uso del servicio contratado. 
Asimismo, aceptas soportar dentro de los límites razonables, riesgos, imperfecciones o indisponibilidad de los servidores. Los programas usados son técnicamente complejos y pueden no haber estado testados con anterioridad sobre todas las posibilidades que existen de uso. Por tanto, renuncias expresamente a reclamar cualquier responsabilidad, contractual o extracontractual, daños y perjuicios a SCRAMBÒTIKA por posibles fallos, lentitud o errores en el acceso y uso del producto contratado.
El acceso y uso del servicio es tu responsabilidad, de tal manera que SCRAMBÒTIKA no se hace responsable de ninguna manera (ni directa ni subsidiaria) de cualquier daño directo o indirecto que pudieras ocasionar a terceros.
En SCRAMBÒTIKA no nos responsabilizamos de:
La contaminación por virus en sus equipos, cuya protección incumbe exclusivamente al cliente.
Las intrusiones de terceros en el servicio, aunque SCRAMBÒTIKA haya establecido medidas razonables de protección.
La configuración defectuosa por tu parte.
Los deterioros o el mal uso de tus equipos.

De los Usuarios 
Eres el único responsable de tu conducta y contenido, y debes respetar y cumplir nuestra política de uso. 
El contenido de los Servicios puede estar protegido por derechos de propiedad intelectual. No copies, subas, descargues ni compartas Contenido a menos que tengas derecho a hacerlo.
Custodia con la máxima precaución tu contraseña para usar ISSUS, asegurándote de que nadie tenga acceso a ella y mantén actualizada la información de tu cuenta.
Aceptas no aplicar ingeniería inversa a los Servicios ni descompilarlos, no intentar hacerlo y no ayudar a nadie a realizar dichas acciones.
Debes cumplir con todos los términos y condiciones de este contrato en el ejercicio de tu actividad profesional, actuando lealmente y de buena fe.
Mediante la contratación de este servicio, el cliente se compromete a mantener operativa, activa y actualizada la dirección e-mail proporcionada en el formulario de contratación para las comunicaciones con SCRAMBÒTIKA, ya que constituye el medio de comunicación preferente de SCRAMBÒTIKA para la gestión ágil y fluida en la prestación del servicio solicitado como consecuencia de la relación contractual que a través de este contrato nos une.
Si quieres cambiar la dirección e-mail facilitada en el formulario de contratación como dirección de contacto deberás hacerlo a través del Área de Cliente, con las medidas propias de autentificación de dicha petición, de manera que en ningún momento quede interrumpida la comunicación entre las partes contratantes. SCRAMBÒTIKA se exonera de toda responsabilidad por las consecuencias que la falta de operatividad de la dirección e-mail del cliente y/o de la falta de comunicación que el cambio de dirección no actualizado pueda producir, así como por la desinformación que alegues debido a la negligencia a la hora de mantener activo este dato.
Reconoces haber testado el producto con tus necesidades y que has sido informado por parte de SCRAMBÒTIKA adecuadamente.
Como cliente, te comprometes a indemnizar a SCRAMBÒTIKA por los gastos que ésta tuviera por imputarte en alguna causa cuya responsabilidad te fuera atribuible, incluidos honorarios y gastos de los abogados, incluso en el caso de decisión judicial no definitiva.
Queda prohibido acceder, modificar, visualizar la configuración, estructura y ficheros de los servidores de SCRAMBÒTIKA. Cualquier problema que se pudiera producir en los servidores y sistemas de seguridad de SCRAMBÒTIKA como consecuencia directa de una actuación negligente, responderías por la responsabilidad civil y penal que te pudiera corresponder. A tal efecto, SCRAMBÒTIKA suspendería temporalmente el servicio. Esta circunstancia se te notificaría para que procedas a solucionar dicha alteración, y si una vez reiniciado el servicio se reincidiera en tal circunstancia de manera continuada o de mala fe, se procedería a una baja del servicio sin derecho a reclamación alguna, por considerar un uso abusivo del servicio contratado.
Con la aceptación del presente contrato, consientes expresamente el envío de las facturas relativas a la prestación del Servicio contratado a través de medios telemáticos, tal y como señala la normativa vigente en esta materia.
6.	Finalización de los Servicios
Eres libre de dejar de utilizar nuestros Servicios en cualquier momento. También nos reservamos el derecho a suspender o cancelar los Servicios en cualquier momento, a nuestra discreción y sin previo aviso. Por ejemplo, podríamos suspender o dar por terminado tu acceso a ISSUS si dejas de cumplir las presentes Condiciones o lo usas de forma que puedas producir responsabilidades legales, realizas un mal uso o lo perturbas por parte de otros usuarios. Por supuesto, te avisaremos mediante la dirección de correo asociada a tu cuenta antes proceder a cualquier acción de este tipo.
El contrato finalizará cuando, además de las causas legalmente establecidas y dispuestas en las distintas cláusulas de este contrato, concurra alguna de las siguientes:
a) Mutuo acuerdo entre las partes.
b) Finalización del período inicial de duración o de las sucesivas prórrogas.
c) Resolución por incumplimiento de alguna de las partes de las obligaciones derivadas del contrato.
d) Cuando cualquiera de las partes se encuentre en situación de quiebra o suspensión de pagos.
Si el incumplimiento fuera causa de la resolución del contrato, SCRAMBÒTIKA se reserva el derecho de finalizar de forma anticipada el presente contrato y, por tanto, desposeerte del servicio contratado sin previo aviso y sin derecho a indemnización ni a devolución de cantidad alguna por tu parte.
7.	Resolución de litigios
Deseamos solucionar tus problemas antes de que sea necesario recurrir a medidas legales, por lo que, antes de registrar una reclamación formal contra SCRAMBÒTIKA, aceptas intentar la resolución de cualquier contencioso informalmente contactando con nosotros. Intentaremos resolver la disputa poniéndonos en contacto contigo por correo electrónico. Si no hemos resuelto el litigio en un plazo de 15 días a partir del envío, cualquiera de las partes podrá registrar una reclamación formal.
8.	Leyes aplicables
Estas Condiciones están sujetas a la legislación española salvo en conflictos de principios de leyes, a menos que lo exija alguna normativa vinculante de cualquier otra jurisdicción.
Las partes firmantes acuerdan que cualquier proceso judicial iniciado para resolver demandas relativas a las Condiciones del servicio se presentará en los juzgados de Sabadell y su partida jurisdiccional.
9.	Contacto
Si tienes alguna duda o pregunta acerca de ISSUS, nuestros Servicios o la política de privacidad, ponte en contacto con nosotros en hola@scrambotika.com.

El equipo de SCRAMBÒTIKA.
