IF OBJECT_ID('[dbo].[Auditory]', 'U')  IS NOT NULL DROP TABLE [dbo].[Auditory]


CREATE TABLE [dbo].[Auditory](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[Type] [int]  NOT NULL,
	[CustomerId] [bigint]  NULL,
	[ProviderId] [bigint]  NULL,
	[Nombre] [nvarchar](150)  NOT NULL,
	[NormaId] [nvarchar](200)  NOT NULL,
	[Amount] [decimal](18,3)  NULL,
	[InternalResponsible] [int]  NOT NULL,
	[Description] [nvarchar](2000)  NULL,
	[Scope] [nvarchar](150)  NULL,
	[EnterpriseAddress] [nvarchar](500)  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[PlannedBy] [int]  NULL,
	[PlannedOn] [datetime]  NULL,
	[ClosedBy] [int]  NULL,
	[ClosedOn] [datetime]  NULL,
	[ValidatedBy] [int]  NULL,
	[ValidatedOn] [datetime]  NULL,
	[ValidatedUserBy] [int]  NULL,
	[ValidatedUserOn] [datetime]  NULL,
	[Status] [int]  NULL,
	[CreatedBy] [int]  NOT NULL,
	[CreatedOn] [datetime]  NOT NULL,
	[ModifiedBy] [int]  NOT NULL,
	[ModifiedOn] [datetime]  NOT NULL,
	[Active] [bit]  NOT NULL,
	[AuditorTeam] [nvarchar](500)  NULL,
	[CompanyAddressId] [int]  NULL,
	[ReportStart] [datetime]  NULL,
	[ReportEnd] [datetime]  NULL,
	[PreviewDate] [datetime]  NULL,
	[PuntosFuertes] [nvarchar](2000)  NULL,
) ON [PRIMARY]