IF OBJECT_ID('[dbo].[BusinessRisk3]', 'U')  IS NOT NULL DROP TABLE [dbo].[BusinessRisk3]


CREATE TABLE [dbo].[BusinessRisk3](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[Description] [varchar](100)  NULL,
	[Code] [bigint]  NOT NULL,
	[RuleId] [bigint]  NOT NULL,
	[ItemDescription] [nvarchar](2000)  NULL,
	[StartControl] [nvarchar](2000)  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[ProbabilityId] [bigint]  NOT NULL,
	[SecurityId] [bigint]  NOT NULL,
	[Result] [int]  NULL,
	[ApplyAction] [bit]  NOT NULL,
	[InitialValue] [int]  NULL,
	[DateStart] [datetime]  NOT NULL,
	[ProcessId] [bigint]  NOT NULL,
	[Assumed] [bit]  NULL,
	[PreviousBusinessRiskId] [bigint]  NULL,
	[Causes] [nvarchar](2000)  NULL,
	[StartAction] [int]  NULL,
	[FinalAction] [int]  NULL,
	[StartProbability] [int]  NULL,
	[StartSeverity] [int]  NULL,
	[StartResult] [int]  NULL,
	[FinalProbability] [int]  NULL,
	[FinalSeverity] [int]  NULL,
	[FinalResult] [int]  NULL,
	[FinalDate] [datetime]  NULL,
	[CreatedBy] [int]  NOT NULL,
	[CreatedOn] [datetime]  NOT NULL,
	[ModifiedBy] [int]  NOT NULL,
	[ModifiedOn] [datetime]  NOT NULL,
	[Active] [bit]  NOT NULL,
) ON [PRIMARY]