IF OBJECT_ID('[dbo].[IncidentAction]', 'U')  IS NOT NULL DROP TABLE [dbo].[IncidentAction]


CREATE TABLE [dbo].[IncidentAction](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[ActionType] [int]  NOT NULL,
	[Description] [nvarchar](100)  NOT NULL,
	[Origin] [int]  NOT NULL,
	[ReporterType] [int]  NOT NULL,
	[DepartmentId] [int]  NULL,
	[ProviderId] [bigint]  NULL,
	[CustomerId] [bigint]  NULL,
	[Number] [bigint]  NOT NULL,
	[IncidentId] [bigint]  NULL,
	[BusinessRiskId] [bigint]  NULL,
	[ObjetivoId] [int]  NULL,
	[OportunityId] [int]  NULL,
	[WhatHappend] [nvarchar](2000)  NOT NULL,
	[WhatHappendBy] [int]  NOT NULL,
	[WhatHappendOn] [datetime]  NOT NULL,
	[Causes] [nvarchar](2000)  NULL,
	[CausesBy] [int]  NULL,
	[CausesOn] [datetime]  NULL,
	[Actions] [nvarchar](2000)  NULL,
	[ActionsBy] [int]  NULL,
	[ActionsOn] [datetime]  NULL,
	[ActionsExecuter] [int]  NULL,
	[ActionsSchedule] [datetime]  NULL,
	[Monitoring] [nvarchar](2000)  NULL,
	[ClosedBy] [int]  NULL,
	[ClosedOn] [datetime]  NULL,
	[ClosedExecutor] [int]  NULL,
	[ClosedExecutorOn] [datetime]  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[Active] [bit]  NOT NULL,
	[CreatedBy] [int]  NULL,
	[CreatedOn] [datetime]  NULL,
	[ModifiedBy] [int]  NOT NULL,
	[ModifiedOn] [datetime]  NOT NULL,
	[AuditoryId] [bigint]  NULL,
) ON [PRIMARY]