IF OBJECT_ID('[dbo].[Incident]', 'U')  IS NOT NULL DROP TABLE [dbo].[Incident]


CREATE TABLE [dbo].[Incident](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[Code] [bigint]  NOT NULL,
	[Origin] [int]  NOT NULL,
	[DepartmentId] [int]  NULL,
	[ProviderId] [bigint]  NULL,
	[CustomerId] [bigint]  NULL,
	[WhatHappendBy] [int]  NOT NULL,
	[WhatHappendOn] [datetime]  NOT NULL,
	[CausesBy] [int]  NULL,
	[CausesOn] [datetime]  NULL,
	[ActionsBy] [int]  NULL,
	[ActionsOn] [datetime]  NULL,
	[ActionsExecuter] [int]  NULL,
	[ActionsSchedule] [datetime]  NULL,
	[ApplyAction] [bit]  NOT NULL,
	[Anotations] [nvarchar](2000)  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[ClosedBy] [int]  NULL,
	[ClosedOn] [datetime]  NULL,
	[Active] [bit]  NULL,
	[ModifiedBy] [int]  NULL,
	[ModifiedOn] [datetime]  NULL,
	[CreatedBy] [int]  NULL,
	[CreatedOn] [datetime]  NULL,
	[Description] [nvarchar](100)  NULL,
	[WhatHappend] [nvarchar](2000)  NULL,
	[Causes] [nvarchar](2000)  NULL,
	[Actions] [nvarchar](2000)  NULL,
) ON [PRIMARY]