IF OBJECT_ID('[dbo].[IncidentAction_bak]', 'U')  IS NOT NULL DROP TABLE [dbo].[IncidentAction_bak]


CREATE TABLE [dbo].[IncidentAction_bak](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[ActionType] [int]  NOT NULL,
	[Origin] [int]  NOT NULL,
	[ReporterType] [int]  NOT NULL,
	[DepartmentId] [int]  NULL,
	[ProviderId] [bigint]  NULL,
	[CustomerId] [bigint]  NULL,
	[Number] [bigint]  NOT NULL,
	[IncidentId] [bigint]  NULL,
	[BusinessRiskId] [bigint]  NULL,
	[WhatHappendBy] [int]  NOT NULL,
	[WhatHappendOn] [datetime]  NOT NULL,
	[CausesBy] [int]  NULL,
	[CausesOn] [datetime]  NULL,
	[ActionsBy] [int]  NULL,
	[ActionsOn] [datetime]  NULL,
	[ActionsExecuter] [int]  NULL,
	[ActionsSchedule] [datetime]  NULL,
	[Monitoring] [nvarchar](2000)  NULL,
	[ClosedBy] [int]  NULL,
	[ClosedOn] [datetime]  NULL,
	[ClosedExecutor] [int]  NULL,
	[ClosedExecutorOn] [datetime]  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[Active] [bit]  NOT NULL,
	[CreatedBy] [int]  NULL,
	[CreatedOn] [datetime]  NULL,
	[ModifiedBy] [int]  NOT NULL,
	[ModifiedOn] [datetime]  NOT NULL,
	[Actions] [nvarchar](2000)  NULL,
	[WhatHappend] [nvarchar](2000)  NULL,
	[Causes] [nvarchar](2000)  NULL,
	[Description] [nvarchar](100)  NULL,
) ON [PRIMARY]