IF OBJECT_ID('[dbo].[Oportunity]', 'U')  IS NOT NULL DROP TABLE [dbo].[Oportunity]


CREATE TABLE [dbo].[Oportunity](
	[Id] [bigint]  NOT NULL,
	[CompanyId] [int]  NOT NULL,
	[Description] [nvarchar](100)  NOT NULL,
	[Code] [bigint]  NOT NULL,
	[ItemDescription] [nvarchar](2000)  NULL,
	[StartControl] [nvarchar](2000)  NULL,
	[Notes] [nvarchar](2000)  NULL,
	[ApplyAction] [bit]  NULL,
	[DateStart] [datetime]  NOT NULL,
	[Causes] [nvarchar](2000)  NULL,
	[Cost] [int]  NULL,
	[Impact] [int]  NULL,
	[Result] [int]  NULL,
	[ProcessId] [bigint]  NOT NULL,
	[RuleId] [bigint]  NOT NULL,
	[AnulateBy] [int]  NULL,
	[AnulateDate] [datetime]  NULL,
	[AnulateReason] [nvarchar](2000)  NULL,
	[FinalCost] [int]  NULL,
	[FinalImpact] [int]  NULL,
	[FinalResult] [int]  NULL,
	[FinalApplyAction] [bit]  NULL,
	[FinalDate] [datetime]  NULL,
	[PreviousOportunityId] [bigint]  NULL,
	[CreatedBy] [int]  NOT NULL,
	[CreatedOn] [datetime]  NOT NULL,
	[ModifiedBy] [int]  NOT NULL,
	[ModifiedOn] [datetime]  NOT NULL,
	[Active] [bit]  NOT NULL,
) ON [PRIMARY]